### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by robsongajunior** [es6rocks/es6rocks.github.io#45]
What IE version we need support?
I opened on IE9 and the stylesheet needs some corrections.

cc/ @jaydson @UltCombo @felipenmoura

**Comment by jaydson** [comment]
IE11+ and Spartan 1+
:p

**Comment by felipenmoura** [comment]
IE10+ ... perhaps, and IE11+.

I said ie10 just because I believe it is working on it, right?
I built most of the html/css/js of the page(although not mentioned anywhere :p ), and worked on it, validating on a Win7 with IE10, when I had to verify IE compatibility. As far as I know, it is "ok" on ie10.
But I would agree that new bugs on ie10 should not be treated as issues, in case new problems appear.
IE11, though, should.
